[2025-05-03T14:58:13.729+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-03T14:58:13.751+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kr_update.trunc manual__2025-05-03T14:52:36.667363+00:00 [queued]>
[2025-05-03T14:58:13.767+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kr_update.trunc manual__2025-05-03T14:52:36.667363+00:00 [queued]>
[2025-05-03T14:58:13.767+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-05-03T14:58:13.785+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): trunc> on 2025-05-03 14:52:36.667363+00:00
[2025-05-03T14:58:13.791+0000] {standard_task_runner.py:72} INFO - Started process 86 to run task
[2025-05-03T14:58:13.795+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kr_update', 'trunc', 'manual__2025-05-03T14:52:36.667363+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/kr_update.py', '--cfg-path', '/tmp/tmpokc8w75m']
[2025-05-03T14:58:13.797+0000] {standard_task_runner.py:105} INFO - Job 37: Subtask trunc
[2025-05-03T14:58:13.859+0000] {task_command.py:467} INFO - Running <TaskInstance: kr_update.trunc manual__2025-05-03T14:52:36.667363+00:00 [running]> on host de293b43eb40
[2025-05-03T14:58:13.964+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kr_update' AIRFLOW_CTX_TASK_ID='trunc' AIRFLOW_CTX_EXECUTION_DATE='2025-05-03T14:52:36.667363+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-03T14:52:36.667363+00:00'
[2025-05-03T14:58:13.966+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-03T14:58:13.970+0000] {kr_update.py:22} INFO - trunc task started
[2025-05-03T14:58:13.971+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/kr_update.py", line 23, in trunc
    with open('/opt/airflow/sql/truncate.sql', 'r') as sql_file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/sql/truncate.sql'
[2025-05-03T14:58:13.990+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=kr_update, task_id=trunc, run_id=manual__2025-05-03T14:52:36.667363+00:00, execution_date=20250503T145236, start_date=20250503T145813, end_date=20250503T145813
[2025-05-03T14:58:14.010+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-03T14:58:14.012+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 37 for task trunc ([Errno 2] No such file or directory: '/opt/airflow/sql/truncate.sql'; 86)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/kr_update.py", line 23, in trunc
    with open('/opt/airflow/sql/truncate.sql', 'r') as sql_file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/sql/truncate.sql'
[2025-05-03T14:58:14.050+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-03T14:58:14.081+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-03T14:58:14.088+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
